version: "3.9"

services:
  server:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/programmers-api
      SPRING_DATASOURCE_USERNAME: foferys
      SPRING_DATASOURCE_PASSWORD: foferys
    networks:
      - postgres

  postgres:
    container_name: factsapi_container
    image: postgres:16
    environment:
      POSTGRES_USER: foferys
      POSTGRES_PASSWORD: foferys
      POSTGRES_DB: programmers-api
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container_facts
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: -admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
