-- Schema iniziale per programmers-api (PostgreSQL)
-- Eseguito automaticamente al primo avvio del container su qualsiasi PC
-- Crea la tabella phrases in PostgreSQL

CREATE TABLE IF NOT EXISTS phrases (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase VARCHAR(255),
    type  VARCHAR(255)
);
