spring.application.name=programmers-jokes-api

# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# # spring.datasource.url=jdbc:mysql://db:3306/programmers-api
# spring.datasource.username=fofedev
# spring.datasource.password=mypass
# spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=update


# postgreSql ----
spring.datasource.url=jdbc:postgresql://localhost:5434/programmers-api
spring.datasource.username=foferys
spring.datasource.password=foferys
spring.jpa.database=POSTGRESQL
spring.servlet.multipart.enabled=true
#  imposta il dialetto che deve usare
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true


# Forza l’esecuzione di data.sql (i dati da inserire nel database postegre creato nel container)
spring.sql.init.mode=always

# IMPORTANTISSIMO: esegue data.sql DOPO JPA
spring.jpa.defer-datasource-initialization=true